<?xml version="1.0"?>

<!-- Puts all the pieces (urdf, control, simulation) of the protobot together -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="protobot">
    <xacro:arg name="prefix" default="" />
    <xacro:arg name="use_gazebo" default="false" />

    <!-- Import different pieces of the protobot -->
    <!-- RVIZ colors -->
    <xacro:include filename="$(find protobot_description)/urdf/materials.urdf.xacro" />

    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="wheel_axis_horizontal_offset" value="${chassis_length - 0.02}"/>
    <xacro:property name="wheel_axis_vertical_offset" value="0.04"/>
    <xacro:property name="wheel_radius" value="0.06"/>

    <!-- Use macros from imported files to define the full protobot -->
    <!-- Core URDF -->
    <xacro:include filename="$(find protobot_description)/urdf/protobot_core.urdf.xacro" />
    <xacro:protobot_core prefix="$(arg prefix)"
        chassis_mass="1.0"
        chassis_length="${chassis_length}"
        chassis_width="0.25"
        chassis_height="0.15"
        wheel_base="0.31"
        wheel_mass="0.2"
        wheel_width="0.030"
        wheel_radius="${wheel_radius}"
        wheel_axis_vertical_offset="${wheel_axis_vertical_offset}"
        wheel_axis_horizontal_offset="${wheel_axis_horizontal_offset}"
        caster_wheel_radius="${wheel_radius - wheel_axis_vertical_offset}"
        caster_wheel_mass="0.1"
    />

    <!-- Camera -->
    <xacro:include filename="$(find protobot_description)/urdf/camera.urdf.xacro" />
    <xacro:camera parent="chassis" prefix="$(arg prefix)" use_gazebo="$(arg use_gazebo)">
        <origin xyz="${chassis_length} 0 0.1" rpy="0 0 0" />
    </xacro:camera>

    <!-- Inertial Measurement Unit (IMU) -->
    <xacro:include filename="$(find protobot_description)/urdf/imu_sensor.urdf.xacro" />
    <xacro:imu_sensor prefix="$(arg prefix)" parent="chassis" use_gazebo="$(arg use_gazebo)">
        <origin xyz="${wheel_axis_horizontal_offset} 0 ${wheel_axis_vertical_offset}" rpy="0 0 0" />
    </xacro:imu_sensor>

    <!-- ROS2 Control -->
    <xacro:include filename="$(find protobot_description)/urdf/protobot_control.urdf.xacro" />
    <xacro:protobot_ros2_control name="protobot" prefix="$(arg prefix)" use_gazebo="$(arg use_gazebo)" />
    
    <!-- Gazebo-specific URDF -->
    <xacro:if value="$(arg use_gazebo)">
        <xacro:include filename="$(find protobot_description)/urdf/protobot_gazebo.urdf.xacro" />
        <xacro:protobot_gazebo prefix="$(arg prefix)"/>
    </xacro:if>

</robot>
